# Generated by Django 5.1.4 on 2025-01-05 21:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text="Tick to make this entry live, if it's good and approved")),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Publication', verbose_name='Publication date')),
                ('body', models.TextField()),
                ('summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('place', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to='entry_media/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entry', 'place'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text="Tick to make this event live, if it's good and approved")),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of Publication', verbose_name='Publication date')),
                ('location', models.CharField(help_text='location or address of event', max_length=400)),
                ('detail', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'events',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
                'indexes': [models.Index(fields=['headline', 'slug', 'is_active', 'pub_date'], name='blog_event_headlin_e6b24e_idx')],
            },
        ),
    ]
